name: Android Build D

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install Android Workloads
      run: ls && tree
      #  dotnet restore workload XEmuera/XEmuera.Android
      #  dotnet workload install android

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the app
      run: dotnet publish --configuration Release -o output

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: output/**/*.apk