name: Android Build E

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Install dependencies
        run: sudo apt-get install -y openjdk-11-jdk

      - name: Install Xamarin.Android
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dotnet.microsoft.com/download/dotnet/7.0/dotnet-sdk-7.0.203-linux-x64.tar.gz
          sudo mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-7.0.100-linux-x64.tar.gz -C $HOME/dotnet
          sudo export PATH=$PATH:$HOME/dotnet

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release