name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Install dependencies
        run: sudo apt-get install -y openjdk-11-jdk

      - name: Install Xamarin.Android
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://download.visualstudio.microsoft.com/download/pr/3c2a8b4d-5e42-4eab-9b3a-1b5e2b8d35a6/2b0d8c5a7fad5c1f1a6c1b5b3a5f2c2b/dotnet-sdk-7.0.100-linux-x64.tar.gz
          sudo mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-7.0.100-linux-x64.tar.gz -C $HOME/dotnet
          sudo export PATH=$PATH:$HOME/dotnet

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release