name: Build Xamarin.Android App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.410'

      - name: Install dependencies
        run: nuget restore XEmuera.sln

      - name: Build APK
        run: msbuild XEmuera\XEmuera.Android/XEmuera.Android.csproj /t:PackageForAndroid /p:Configuration=Release /p:AndroidPackageFormat=apk

      - name: Zip the build folder
        run: |
          $apkFolderPath = "bin\Release\android\Xamarin.Android\bin\Release\"
          Compress-Archive -Path $apkFolderPath -DestinationPath $apkFolderPath.zip

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: bin\Release\android\Xamarin.Android\bin\Release\*.zip
