name: Build APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  ANDROID_HOME: /usr/local/lib/android/sdk/


jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.410' # Adjust the version as needed

      - name: Install Xamarin.Android
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main" > /etc/apt/sources.list.d/teams.list'
          sudo apt-get update
          sudo apt-get install -y mono-devel
          sudo apt-get install -y dotnet-sdk-8.0
          sudo apt-get install -y openjdk-11-jdk
          sudo apt-get install -y unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip commandlinetools-linux-6858069_latest.zip -d $ANDROID_HOME/cmdline-tools
          yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
          $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-28" "build-tools;28.0.3"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build APK
        run: dotnet build -c Release